CREATE TABLE IF NOT EXISTS preferred_companies (
  name TEXT PRIMARY KEY,
  tier INTEGER NOT NULL DEFAULT 2,
  category TEXT NOT NULL DEFAULT 'general'
);

INSERT OR IGNORE INTO preferred_companies (name, tier, category) VALUES

-- ── TIER 1: SECURITY / NHI / SECRETS / APPSEC (direct talent pools) ──

-- Secrets detection & data security posture
('Nightfall AI', 1, 'cyber_security'),
('Cyberhaven', 1, 'cyber_security'),
('BigID', 1, 'cyber_security'),
('Dig Security', 1, 'cyber_security'),
('Sentra', 1, 'cyber_security'),
('Cyera', 1, 'cyber_security'),
('Laminar Security', 1, 'cyber_security'),
('Polar Security', 1, 'cyber_security'),
('Normalyze', 1, 'cyber_security'),
('Open Raven', 1, 'cyber_security'),
('Securiti', 1, 'cyber_security'),
('Code42', 1, 'cyber_security'),
('Spirion', 1, 'cyber_security'),
('Varonis', 1, 'cyber_security'),

-- Secrets / credential vaults
('HashiCorp', 1, 'cyber_security'),
('Doppler', 1, 'cyber_security'),
('Infisical', 1, 'cyber_security'),
('Akeyless', 1, 'cyber_security'),
('1Password', 1, 'cyber_security'),
('Bitwarden', 1, 'cyber_security'),
('Dashlane', 1, 'cyber_security'),
('Passbolt', 1, 'cyber_security'),
('LastPass', 1, 'cyber_security'),
('Keeper Security', 1, 'cyber_security'),

-- Identity, PAM & PKI
('CyberArk', 1, 'cyber_security'),
('BeyondTrust', 1, 'cyber_security'),
('Delinea', 1, 'cyber_security'),
('Saviynt', 1, 'cyber_security'),
('SailPoint', 1, 'cyber_security'),
('Okta', 1, 'cyber_security'),
('Teleport', 1, 'cyber_security'),
('Venafi', 1, 'cyber_security'),
('Keyfactor', 1, 'cyber_security'),
('AppViewX', 1, 'cyber_security'),
('Ping Identity', 1, 'cyber_security'),
('ForgeRock', 1, 'cyber_security'),
('Auth0', 1, 'cyber_security'),
('Stytch', 1, 'cyber_security'),
('WorkOS', 1, 'cyber_security'),
('GlobalSign', 1, 'cyber_security'),
('DigiCert', 1, 'cyber_security'),

-- API Security
('Salt Security', 1, 'cyber_security'),
('Noname Security', 1, 'cyber_security'),
('Traceable AI', 1, 'cyber_security'),
('42Crunch', 1, 'cyber_security'),
('Escape', 1, 'cyber_security'),
('APIsec', 1, 'cyber_security'),
('FireTail', 1, 'cyber_security'),
('Pynt', 1, 'cyber_security'),

-- Application Security / SAST / SCA / Supply Chain
('Snyk', 1, 'cyber_security'),
('Semgrep', 1, 'cyber_security'),
('Checkmarx', 1, 'cyber_security'),
('Veracode', 1, 'cyber_security'),
('Synopsys', 1, 'cyber_security'),
('Mend', 1, 'cyber_security'),
('FOSSA', 1, 'cyber_security'),
('Sonatype', 1, 'cyber_security'),
('Ox Security', 1, 'cyber_security'),
('Cycode', 1, 'cyber_security'),
('Legit Security', 1, 'cyber_security'),
('Endor Labs', 1, 'cyber_security'),
('Chainguard', 1, 'cyber_security'),
('Aikido Security', 1, 'cyber_security'),
('Apiiro', 1, 'cyber_security'),
('Arnica', 1, 'cyber_security'),
('Jit', 1, 'cyber_security'),
('Bearer', 1, 'cyber_security'),
('Deep Factor', 1, 'cyber_security'),
('Sonar', 1, 'cyber_security'),
('SonarQube', 1, 'cyber_security'),

-- Cloud Security / CSPM / CNAPP
('Wiz', 1, 'cyber_security'),
('Orca Security', 1, 'cyber_security'),
('Lacework', 1, 'cyber_security'),
('Aqua Security', 1, 'cyber_security'),
('Sysdig', 1, 'cyber_security'),
('Prisma Cloud', 1, 'cyber_security'),
('Drata', 1, 'cyber_security'),
('Vanta', 1, 'cyber_security'),
('Secureframe', 1, 'cyber_security'),
('ARMO', 1, 'cyber_security'),
('Wiz', 1, 'cyber_security'),

-- Threat Intelligence
('Mandiant', 1, 'cyber_security'),
('Recorded Future', 1, 'cyber_security'),
('Anomali', 1, 'cyber_security'),
('ThreatConnect', 1, 'cyber_security'),
('Flashpoint', 1, 'cyber_security'),
('Cybersixgill', 1, 'cyber_security'),
('ZeroFOX', 1, 'cyber_security'),
('Intel 471', 1, 'cyber_security'),
('Cyberint', 1, 'cyber_security'),
('EclecticIQ', 1, 'cyber_security'),
('Digital Shadows', 1, 'cyber_security'),
('Filigran', 1, 'cyber_security'),
('CrowdSec', 1, 'cyber_security'),
('BforeAI', 1, 'cyber_security'),
('Stamus Networks', 1, 'cyber_security'),
('Silobreaker', 1, 'cyber_security'),
('GroupIB', 1, 'cyber_security'),

-- EDR / MDR / XDR
('CrowdStrike', 1, 'cyber_security'),
('SentinelOne', 1, 'cyber_security'),
('Cybereason', 1, 'cyber_security'),
('Carbon Black', 1, 'cyber_security'),
('Huntress', 1, 'cyber_security'),
('ThreatLocker', 1, 'cyber_security'),
('Darktrace', 1, 'cyber_security'),
('Vectra AI', 1, 'cyber_security'),
('ExtraHop', 1, 'cyber_security'),
('Arctic Wolf', 1, 'cyber_security'),
('Stellar Cyber', 1, 'cyber_security'),

-- Network / SASE / Zero Trust
('Cloudflare', 1, 'cyber_security'),
('Zscaler', 1, 'cyber_security'),
('Netskope', 1, 'cyber_security'),
('Illumio', 1, 'cyber_security'),
('Akamai', 1, 'cyber_security'),
('Fastly', 1, 'cyber_security'),
('Twingate', 1, 'cyber_security'),
('Tailscale', 1, 'cyber_security'),

-- Vulnerability Management
('Tenable', 1, 'cyber_security'),
('Qualys', 1, 'cyber_security'),
('Rapid7', 1, 'cyber_security'),
('Outpost24', 1, 'cyber_security'),
('Detectify', 1, 'cyber_security'),
('Nucleus Security', 1, 'cyber_security'),
('Vulcan Cyber', 1, 'cyber_security'),

-- Bug Bounty & Offensive Security
('HackerOne', 1, 'cyber_security'),
('Bugcrowd', 1, 'cyber_security'),
('Cobalt', 1, 'cyber_security'),
('Synack', 1, 'cyber_security'),
('YesWeHack', 1, 'cyber_security'),
('Intigriti', 1, 'cyber_security'),

-- Established security vendors (large talent pools)
('Check Point', 1, 'cyber_security'),
('Fortinet', 1, 'cyber_security'),
('Palo Alto Networks', 1, 'cyber_security'),
('Sophos', 1, 'cyber_security'),
('Trend Micro', 1, 'cyber_security'),
('Bitdefender', 1, 'cyber_security'),
('ESET', 1, 'cyber_security'),
('WithSecure', 1, 'cyber_security'),
('Malwarebytes', 1, 'cyber_security'),
('KnowBe4', 1, 'cyber_security'),
('Proofpoint', 1, 'cyber_security'),
('Mimecast', 1, 'cyber_security'),
('Abnormal Security', 1, 'cyber_security'),
('Barracuda Networks', 1, 'cyber_security'),
('Tanium', 1, 'cyber_security'),
('Imperva', 1, 'cyber_security'),
('Secureworks', 1, 'cyber_security'),

-- Email & Phishing Security
('Tessian', 1, 'cyber_security'),
('Ironscales', 1, 'cyber_security'),
('SlashNext', 1, 'cyber_security'),
('Material Security', 1, 'cyber_security'),
('Sublime Security', 1, 'cyber_security'),
('Cofense', 1, 'cyber_security'),
('Hoxhunt', 1, 'cyber_security'),
('Vade Secure', 1, 'cyber_security'),

-- SIEM / SOAR
('Splunk', 1, 'cyber_security'),
('Elastic Security', 1, 'cyber_security'),
('Securonix', 1, 'cyber_security'),
('Exabeam', 1, 'cyber_security'),
('Devo', 1, 'cyber_security'),
('Hunters', 1, 'cyber_security'),
('LogRhythm', 1, 'cyber_security'),

-- Bot / fraud
('DataDome', 1, 'cyber_security'),

-- French cyber ecosystem
('CybelAngel', 1, 'french_cyber'),
('Riot', 1, 'french_cyber'),
('Qevlar AI', 1, 'french_cyber'),
('MokN', 1, 'french_cyber'),
('CyberVadis', 1, 'french_cyber'),
('TrustInSoft', 1, 'french_cyber'),
('Elba', 1, 'french_cyber'),
('Pradeo', 1, 'french_cyber'),
('NEVERHACK', 1, 'french_cyber'),
('Stormshield', 1, 'french_cyber'),
('Intrinsec', 1, 'french_cyber'),
('I-TRACING', 1, 'french_cyber'),
('Data Theorem', 1, 'french_cyber'),
('EfficientIP', 1, 'french_cyber'),
('Cryptosense', 1, 'french_cyber'),
('Sqreen', 1, 'french_cyber'),

-- ── TIER 2: ALL TECH — STARTUPS, SCALE-UPS, BIG TECH ──

-- Developer tools & platform
('GitHub', 2, 'dev_tools'),
('GitLab', 2, 'dev_tools'),
('Bitbucket', 2, 'dev_tools'),
('CircleCI', 2, 'dev_tools'),
('BuildKite', 2, 'dev_tools'),
('Harness', 2, 'dev_tools'),
('JFrog', 2, 'dev_tools'),
('Sonatype', 2, 'dev_tools'),
('Pulumi', 2, 'dev_tools'),
('Spacelift', 2, 'dev_tools'),
('Scalr', 2, 'dev_tools'),
('Env0', 2, 'dev_tools'),
('Docker', 2, 'dev_tools'),
('Red Hat', 2, 'dev_tools'),
('SUSE', 2, 'dev_tools'),
('Rancher', 2, 'dev_tools'),
('Anchore', 2, 'dev_tools'),
('Retool', 2, 'dev_tools'),
('Appsmith', 2, 'dev_tools'),
('Tooljet', 2, 'dev_tools'),
('Linear', 2, 'dev_tools'),
('Notion', 2, 'dev_tools'),
('Figma', 2, 'dev_tools'),
('Loom', 2, 'dev_tools'),
('Miro', 2, 'dev_tools'),
('Postman', 2, 'dev_tools'),
('Insomnia', 2, 'dev_tools'),
('Stoplight', 2, 'dev_tools'),
('ReadMe', 2, 'dev_tools'),
('Swagger', 2, 'dev_tools'),
('CoderPad', 2, 'dev_tools'),
('SmartBear', 2, 'dev_tools'),
('Perforce', 2, 'dev_tools'),
('Tricentis', 2, 'dev_tools'),
('Mabl', 2, 'dev_tools'),
('LaunchDarkly', 2, 'dev_tools'),
('Split', 2, 'dev_tools'),

-- Cloud PaaS / Infrastructure
('Platform.sh', 2, 'dev_infra'),
('Render', 2, 'dev_infra'),
('Fly.io', 2, 'dev_infra'),
('Qovery', 2, 'dev_infra'),
('Railway', 2, 'dev_infra'),
('Vercel', 2, 'dev_infra'),
('Netlify', 2, 'dev_infra'),
('Supabase', 2, 'dev_infra'),
('PlanetScale', 2, 'dev_infra'),
('Neon', 2, 'dev_infra'),
('Turso', 2, 'dev_infra'),
('Cloudflare Workers', 2, 'dev_infra'),
('Temporal', 2, 'dev_infra'),
('Deno', 2, 'dev_infra'),

-- API / Integration
('Gravitee', 2, 'dev_tools'),
('Traefik Labs', 2, 'dev_tools'),
('Kong', 2, 'dev_tools'),
('Tyk', 2, 'dev_tools'),
('Apigee', 2, 'dev_tools'),
('MuleSoft', 2, 'dev_tools'),
('Nango', 2, 'dev_tools'),
('Merge', 2, 'dev_tools'),
('Codat', 2, 'dev_tools'),
('Zapier', 2, 'dev_tools'),
('Make', 2, 'dev_tools'),
('n8n', 2, 'dev_tools'),

-- Observability & Monitoring
('Datadog', 2, 'observability'),
('Dynatrace', 2, 'observability'),
('New Relic', 2, 'observability'),
('Grafana Labs', 2, 'observability'),
('PagerDuty', 2, 'observability'),
('Honeycomb', 2, 'observability'),
('Lightstep', 2, 'observability'),
('Elastic', 2, 'observability'),
('Sumo Logic', 2, 'observability'),
('Humio', 2, 'observability'),
('Chronosphere', 2, 'observability'),
('Coralogix', 2, 'observability'),
('Logz.io', 2, 'observability'),

-- Data Engineering & DataOps
('dbt Labs', 2, 'data_eng'),
('Fivetran', 2, 'data_eng'),
('Airbyte', 2, 'data_eng'),
('Astronomer', 2, 'data_eng'),
('Dagster', 2, 'data_eng'),
('Prefect', 2, 'data_eng'),
('Kestra', 2, 'data_eng'),
('Conduktor', 2, 'data_eng'),
('Sifflet', 2, 'data_eng'),
('DataGalaxy', 2, 'data_eng'),
('Linkurious', 2, 'data_eng'),
('CastorDoc', 2, 'data_eng'),
('Anomalo', 2, 'data_eng'),
('Monte Carlo', 2, 'data_eng'),
('Atlan', 2, 'data_eng'),
('Alation', 2, 'data_eng'),
('Collibra', 2, 'data_eng'),
('Talend', 2, 'data_eng'),
('Matillion', 2, 'data_eng'),
('Stitch', 2, 'data_eng'),
('Census', 2, 'data_eng'),
('Hightouch', 2, 'data_eng'),
('Dataiku', 2, 'data_eng'),

-- AI & ML Infrastructure
('Mistral AI', 2, 'ai_infra'),
('Hugging Face', 2, 'ai_infra'),
('Cohere', 2, 'ai_infra'),
('Anthropic', 2, 'ai_infra'),
('OpenAI', 2, 'ai_infra'),
('Scale AI', 2, 'ai_infra'),
('Weights & Biases', 2, 'ai_infra'),
('MLflow', 2, 'ai_infra'),
('BentoML', 2, 'ai_infra'),
('Replicate', 2, 'ai_infra'),
('Modal', 2, 'ai_infra'),
('Together AI', 2, 'ai_infra'),
('Groq', 2, 'ai_infra'),
('Anyscale', 2, 'ai_infra'),
('Lightning AI', 2, 'ai_infra'),
('Pathway', 2, 'ai_infra'),
('Phospho', 2, 'ai_infra'),
('Adaptive ML', 2, 'ai_infra'),
('Dust', 2, 'ai_infra'),
('Langchain', 2, 'ai_infra'),
('Crew AI', 2, 'ai_infra'),

-- French tech — security adjacent
('Algolia', 2, 'french_tech'),
('Strapi', 2, 'french_tech'),
('Lago', 2, 'french_tech'),
('Windmill', 2, 'french_tech'),
('Qovery', 2, 'french_tech'),
('Conduktor', 2, 'french_tech'),
('Kestra', 2, 'french_tech'),
('Phospho', 2, 'french_tech'),
('Pathway', 2, 'french_tech'),
('Sifflet', 2, 'french_tech'),
('DataGalaxy', 2, 'french_tech'),
('Linkurious', 2, 'french_tech'),
('CastorDoc', 2, 'french_tech'),

-- French scale-ups
('Brevo', 2, 'french_tech'),
('Aircall', 2, 'french_tech'),
('Pigment', 2, 'french_tech'),
('Front', 2, 'french_tech'),
('Akeneo', 2, 'french_tech'),
('Contentsquare', 2, 'french_tech'),
('Shift Technology', 2, 'french_tech'),
('Didomi', 2, 'french_tech'),
('Pennylane', 2, 'french_tech'),
('Payfit', 2, 'french_tech'),
('Qonto', 2, 'french_tech'),
('Alan', 2, 'french_tech'),
('Spendesk', 2, 'french_tech'),
('Swile', 2, 'french_tech'),
('Lucca', 2, 'french_tech'),
('Malt', 2, 'french_tech'),
('Comet', 2, 'french_tech'),
('Welcome to the Jungle', 2, 'french_tech'),
('Lempire', 2, 'french_tech'),
('Chili Piper', 2, 'french_tech'),
('Botify', 2, 'french_tech'),
('360Learning', 2, 'french_tech'),
('Livestorm', 2, 'french_tech'),
('Slite', 2, 'french_tech'),
('Klaxoon', 2, 'french_tech'),
('CoderPad', 2, 'french_tech'),
('Ringover', 2, 'french_tech'),
('Odaseva', 2, 'french_tech'),
('Gorgias', 2, 'french_tech'),
('Traefik Labs', 2, 'french_tech'),
('Gravitee', 2, 'french_tech'),
('Nango', 2, 'french_tech'),
('Platform.sh', 2, 'french_tech'),
('Photoroom', 2, 'french_tech'),
('Claap', 2, 'french_tech'),
('Elba', 2, 'french_tech'),
('Sweep', 2, 'french_tech'),
('Twenty', 2, 'french_tech'),
('Topo', 2, 'french_tech'),
('Surfe', 2, 'french_tech'),
('Leadbay', 2, 'french_tech'),
('Kpler', 2, 'french_tech'),
('Skello', 2, 'french_tech'),
('Shadow', 2, 'french_tech'),
('Kameleoon', 2, 'french_tech'),
('YesWeHack', 2, 'french_tech'),
('Doctrine', 2, 'french_tech'),
('Livestorm', 2, 'french_tech'),
('Semarchy', 2, 'french_tech'),
('Greenly', 2, 'french_tech'),
('Trustpair', 2, 'french_tech'),
('Leanspace', 2, 'french_tech'),
('Conduktor', 2, 'french_tech'),
('Opendatasoft', 2, 'french_tech'),
('Opensee', 2, 'french_tech'),
('Gladia', 2, 'french_tech'),
('Mindee', 2, 'french_tech'),
('Kili Technology', 2, 'french_tech'),
('Upflow', 2, 'french_tech'),
('Agicap', 2, 'french_tech'),
('Formance', 2, 'french_tech'),
('Scaleflex', 2, 'french_tech'),

-- SaaS / B2B Scale-ups (international)
('HubSpot', 2, 'saas_scaleup'),
('Salesforce', 2, 'saas_scaleup'),
('Zendesk', 2, 'saas_scaleup'),
('Intercom', 2, 'saas_scaleup'),
('Freshworks', 2, 'saas_scaleup'),
('Pipedrive', 2, 'saas_scaleup'),
('Copper', 2, 'saas_scaleup'),
('Close', 2, 'saas_scaleup'),
('Outreach', 2, 'saas_scaleup'),
('Salesloft', 2, 'saas_scaleup'),
('Gong', 2, 'saas_scaleup'),
('Chorus', 2, 'saas_scaleup'),
('Clari', 2, 'saas_scaleup'),
('Amplitude', 2, 'saas_scaleup'),
('Mixpanel', 2, 'saas_scaleup'),
('Segment', 2, 'saas_scaleup'),
('Heap', 2, 'saas_scaleup'),
('PostHog', 2, 'saas_scaleup'),
('Pendo', 2, 'saas_scaleup'),
('Contentful', 2, 'saas_scaleup'),
('Sanity', 2, 'saas_scaleup'),
('Storyblok', 2, 'saas_scaleup'),
('Webflow', 2, 'saas_scaleup'),
('Ghost', 2, 'saas_scaleup'),
('Airtable', 2, 'saas_scaleup'),
('Coda', 2, 'saas_scaleup'),
('ClickUp', 2, 'saas_scaleup'),
('Asana', 2, 'saas_scaleup'),
('Monday.com', 2, 'saas_scaleup'),
('Basecamp', 2, 'saas_scaleup'),
('Atlassian', 2, 'saas_scaleup'),
('Slack', 2, 'saas_scaleup'),
('Twilio', 2, 'saas_scaleup'),
('Sendgrid', 2, 'saas_scaleup'),
('Vonage', 2, 'saas_scaleup'),
('Stripe', 2, 'saas_scaleup'),
('Braintree', 2, 'saas_scaleup'),
('Adyen', 2, 'saas_scaleup'),
('Checkout.com', 2, 'saas_scaleup'),
('GoCardless', 2, 'saas_scaleup'),
('Klarna', 2, 'saas_scaleup'),
('Payoneer', 2, 'saas_scaleup'),
('Square', 2, 'saas_scaleup'),
('Plaid', 2, 'saas_scaleup'),
('Brex', 2, 'saas_scaleup'),
('Ramp', 2, 'saas_scaleup'),
('Spendesk', 2, 'saas_scaleup'),
('Coupa', 2, 'saas_scaleup'),
('Workday', 2, 'saas_scaleup'),
('ServiceNow', 2, 'saas_scaleup'),
('Zendesk', 2, 'saas_scaleup'),
('Freshworks', 2, 'saas_scaleup'),
('Jira', 2, 'saas_scaleup'),
('Confluence', 2, 'saas_scaleup'),

-- Cloud & Infrastructure
('Amazon Web Services', 2, 'big_tech'),
('Google Cloud', 2, 'big_tech'),
('Microsoft Azure', 2, 'big_tech'),
('Snowflake', 2, 'big_tech'),
('Databricks', 2, 'big_tech'),
('MongoDB', 2, 'big_tech'),
('Redis', 2, 'big_tech'),
('Cockroach Labs', 2, 'big_tech'),
('ClickHouse', 2, 'big_tech'),
('Citus Data', 2, 'big_tech'),
('Timescale', 2, 'big_tech'),
('SingleStore', 2, 'big_tech'),

-- Big Tech (senior security hires)
('Google', 2, 'big_tech'),
('Microsoft', 2, 'big_tech'),
('Meta', 2, 'big_tech'),
('Amazon', 2, 'big_tech'),
('Apple', 2, 'big_tech'),
('Netflix', 2, 'big_tech'),
('Stripe', 2, 'big_tech'),
('Uber', 2, 'big_tech'),
('LinkedIn', 2, 'big_tech'),
('Dropbox', 2, 'big_tech'),
('Twitter', 2, 'big_tech'),
('Spotify', 2, 'big_tech'),
('Airbnb', 2, 'big_tech'),
('Lyft', 2, 'big_tech'),
('Pinterest', 2, 'big_tech'),
('Snap', 2, 'big_tech'),
('Adobe', 2, 'big_tech'),
('Oracle', 2, 'big_tech'),
('SAP', 2, 'big_tech'),
('IBM', 2, 'big_tech'),
('Cisco', 2, 'big_tech'),
('VMware', 2, 'big_tech'),
('Broadcom', 2, 'big_tech'),
('HP Enterprise', 2, 'big_tech'),
('Dell Technologies', 2, 'big_tech'),
('Juniper Networks', 2, 'big_tech'),
('Arista Networks', 2, 'big_tech'),

-- Next 120 / French Next 40 recent additions
('Mistral AI', 2, 'french_tech'),
('H Company', 2, 'french_tech'),
('Bioptimus', 2, 'french_tech'),
('Poolside', 2, 'french_tech'),
('Nabla', 2, 'french_tech'),
('Exotec', 2, 'french_tech'),
('Filigran', 2, 'french_tech'),
('Escape', 2, 'french_tech'),

-- US security startups (Next120 / Next500 analogs)
('Dope Security', 2, 'cyber_security'),
('RunZero', 2, 'cyber_security'),
('Grip Security', 2, 'cyber_security'),
('Astrix Security', 1, 'cyber_security'),
('Entro Security', 1, 'cyber_security'),
('Opal Security', 1, 'cyber_security'),
('Access Control Labs', 1, 'cyber_security'),
('Valence Security', 1, 'cyber_security'),
('Reco AI', 1, 'cyber_security'),
('Obsidian Security', 1, 'cyber_security'),
('Wing Security', 1, 'cyber_security'),
('Nudge Security', 1, 'cyber_security'),
('Torq', 2, 'cyber_security'),
('Tines', 2, 'cyber_security'),
('Swimlane', 2, 'cyber_security'),
('Splunk', 2, 'cyber_security'),
('Cribl', 2, 'cyber_security'),
('Exabeam', 2, 'cyber_security'),
('Hunters', 2, 'cyber_security'),
('Query.AI', 2, 'cyber_security'),
('Axonius', 2, 'cyber_security'),
('Armis', 2, 'cyber_security'),
('Claroty', 2, 'cyber_security'),
('Dragos', 2, 'cyber_security'),
('Nozomi Networks', 2, 'cyber_security'),
('Forescout', 2, 'cyber_security'),
('Medigate', 2, 'cyber_security'),
('Phosphorus Cybersecurity', 2, 'cyber_security'),
('Ordr', 2, 'cyber_security');
